import { Skill, Contributor, ActivityItem, Stats, SkillDependency, CertificationDetails } from "./types";

// Reusable dependency sets
const PLAYWRIGHT_DEPS: SkillDependency[] = [
  { name: "PLAYWRIGHT_BROWSER_PATH", type: "env", required: false, description: "Playwright 浏览器可执行路径", default: "自动检测" },
  { name: "playwright", type: "package", required: true, description: "Playwright 自动化库 >= 1.30.0" },
  { name: "chromium / firefox / webkit", type: "tool", required: true, description: "至少安装一种浏览器驱动" },
];

const FEISHU_DEPS: SkillDependency[] = [
  { name: "FEISHU_APP_ID", type: "env", required: true, description: "飞书开放平台应用 App ID" },
  { name: "FEISHU_APP_SECRET", type: "env", required: true, description: "飞书开放平台应用 App Secret" },
  { name: "feishu-sdk", type: "package", required: true, description: "飞书 OpenAPI SDK >= 2.0.0" },
];

const GITHUB_DEPS: SkillDependency[] = [
  { name: "GITHUB_TOKEN", type: "env", required: true, description: "GitHub Personal Access Token（需 repo 权限）" },
  { name: "octokit", type: "package", required: true, description: "GitHub REST API 客户端 >= 3.0.0" },
];

const NOTION_DEPS: SkillDependency[] = [
  { name: "NOTION_API_KEY", type: "env", required: true, description: "Notion Integration Token" },
  { name: "NOTION_DATABASE_ID", type: "env", required: false, description: "默认写入的数据库 ID", default: "运行时指定" },
  { name: "@notionhq/client", type: "package", required: true, description: "Notion 官方 SDK >= 2.2.0" },
];

// ── Certification detail helpers ──────────────────────────────────────────────

const SAFETY_CHECKS_PASSED = [
  { id: "sc-1", name: "危险操作识别", status: "passed" as const },
  { id: "sc-2", name: "提示注入抗干扰检测", status: "passed" as const },
  { id: "sc-3", name: "模糊/无约束指令拦截", status: "passed" as const },
  { id: "sc-4", name: "风险命令检测", status: "passed" as const },
  { id: "sc-5", name: "恶意代码检测", status: "passed" as const },
  { id: "sc-6", name: "绿网内容安全检测", status: "passed" as const },
  { id: "sc-7", name: "API Key 窃取检测", status: "passed" as const },
];

const SAFETY_CHECKS_PARTIAL = [
  { id: "sc-1", name: "危险操作识别", status: "passed" },
  { id: "sc-2", name: "提示注入抗干扰检测", status: "passed" },
  { id: "sc-3", name: "模糊/无约束指令拦截", status: "passed" },
  { id: "sc-4", name: "风险命令检测", status: "pending" },
  { id: "sc-5", name: "恶意代码检测", status: "passed" },
  { id: "sc-6", name: "绿网内容安全检测", status: "pending" },
  { id: "sc-7", name: "API Key 窃取检测", status: "passed" },
];

const COMPLETENESS_FULL = [
  { id: "cc-1", name: "README.md 已声明", detail: "包含功能说明、安装步骤、使用示例及权限声明", status: "passed" as const },
  { id: "cc-2", name: "skill.md 已声明", detail: "技能入口、参数与约束均已在 skill.md 中明确定义", status: "passed" as const },
  { id: "cc-3", name: "依赖项已声明", detail: "所有必填与可选依赖均已列出，无隐式依赖", status: "passed" as const },
  { id: "cc-4", name: "运行环境已说明", detail: "已标注所需运行时（Node.js ≥ 18 / Python ≥ 3.10 等）", status: "passed" as const },
  { id: "cc-5", name: "数据配置已说明", detail: "AK、Cookie、Token 等敏感配置均有说明及注入方式", status: "passed" as const },
];

const COMPLETENESS_PARTIAL = [
  { id: "cc-1", name: "README.md 已声明", detail: "包含功能说明、安装步骤、使用示例及权限声明", status: "passed" as const },
  { id: "cc-2", name: "skill.md 已声明", detail: "技能入口已定义，但部分参数约束描述不完整", status: "passed" as const },
  { id: "cc-3", name: "依赖项已声明", detail: "所有必填与可选依赖均已列出，无隐式依赖", status: "passed" as const },
  { id: "cc-4", name: "运行环境已说明", detail: "已标注所需运行时", status: "passed" as const },
  { id: "cc-5", name: "数据配置已说明", detail: "部分敏感配置未说明注入方式，需补全", status: "pending" as const },
];

const CERT_VERIFIED_SF: CertificationDetails = {
  safety: {
    checks: SAFETY_CHECKS_PASSED,
    testedAt: "2026-03-09",
  },
  completeness: {
    items: COMPLETENESS_FULL,
    testedAt: "2026-03-09",
  },
  executability: {
    sandboxEnv: "Node.js 20 · Alpine Linux 3.19 · 隔离网络",
    humanReviewed: true,
    testedAt: "2026-03-09",
    testCases: [
      {
        id: "tc-1",
        name: "技能搜索匹配",
        input: "帮我处理 Excel 数据并生成图表",
        expectedOutput: "推荐 excel-reader + data-visualizer 两个 skill",
        actualOutput: "推荐 excel-reader + data-visualizer，置信度 0.94",
        passed: true,
      },
      {
        id: "tc-2",
        name: "精确名称查找",
        input: "安装 browser-automation",
        expectedOutput: "返回 browser-automation skill 详情及安装指令",
        actualOutput: "返回 browser-automation v2.3.1 详情，含 3 步安装指令",
        passed: true,
      },
      {
        id: "tc-3",
        name: "无匹配结果处理",
        input: "我要一个能控制咖啡机的 skill",
        expectedOutput: "返回「暂无匹配」并给出相近推荐",
        actualOutput: "返回「暂无匹配」，推荐 iot-controller 作为替代",
        passed: true,
      },
      {
        id: "tc-4",
        name: "多轮对话上下文保留",
        input: "上一个推荐的 skill 有没有飞书版本？",
        expectedOutput: "基于上文记忆给出飞书相关 skill",
        actualOutput: "基于上下文推荐 feishu-integration，匹配准确",
        passed: true,
      },
      {
        id: "tc-5",
        name: "安装失败后重试引导",
        input: "安装失败了，提示找不到 npm",
        expectedOutput: "给出 npm 安装指引并提供备用安装方式",
        actualOutput: "输出 npm 安装文档链接及 skillhub CLI 备用方式",
        passed: true,
      },
    ],
  },
};

const CERT_VERIFIED_BROWSER: CertificationDetails = {
  safety: {
    checks: SAFETY_CHECKS_PASSED,
    testedAt: "2026-03-05",
  },
  completeness: {
    items: COMPLETENESS_FULL,
    testedAt: "2026-03-05",
  },
  executability: {
    sandboxEnv: "Node.js 20 · Chromium 123 · 隔离网络沙箱",
    humanReviewed: true,
    testedAt: "2026-03-05",
    testCases: [
      {
        id: "tc-1",
        name: "页面导航与截图",
        input: "打开 https://example.com 并截图保存为 out.png",
        expectedOutput: "成功截图，文件写入 out.png",
        actualOutput: "成功截图，文件写入 out.png（2.4 KB）",
        passed: true,
      },
      {
        id: "tc-2",
        name: "表单填写与提交",
        input: "在登录页填写用户名 test@test.com 和密码 ****，点击提交",
        expectedOutput: "表单填写完成，页面跳转至仪表盘",
        actualOutput: "表单填写完成，页面跳转至 /dashboard",
        passed: true,
      },
      {
        id: "tc-3",
        name: "数据抓取",
        input: "抓取页面所有产品名称和价格，返回 JSON",
        expectedOutput: "返回包含 name/price 字段的 JSON 数组",
        actualOutput: "返回 [{name,price}×12] JSON 数组",
        passed: true,
      },
      {
        id: "tc-4",
        name: "多标签页管理",
        input: "同时打开 3 个标签页并截图",
        expectedOutput: "3 个标签页均截图成功",
        actualOutput: "3 个标签页截图成功，耗时 4.2 s",
        passed: true,
      },
      {
        id: "tc-5",
        name: "动态内容等待",
        input: "等待页面加载完成后再截图（含 SPA 路由跳转）",
        expectedOutput: "等待 networkidle 后截图，内容完整",
        actualOutput: "等待 networkidle 2 s 后截图，内容完整",
        passed: true,
      },
    ],
  },
};

const CERT_REVIEWED_FEISHU: CertificationDetails = {
  safety: {
    checks: SAFETY_CHECKS_PASSED,
    testedAt: "2026-03-01",
  },
  completeness: {
    items: COMPLETENESS_PARTIAL,
    testedAt: "2026-03-01",
  },
  executability: {
    sandboxEnv: "Node.js 18 · 飞书沙盒应用环境",
    humanReviewed: false,
    testedAt: "2026-03-01",
    testCases: [
      {
        id: "tc-1",
        name: "发送文本消息",
        input: "向 user_id=ou_xxx 发送消息「任务完成」",
        expectedOutput: "API 返回 code:0，消息发送成功",
        actualOutput: "API 返回 code:0，消息发送成功",
        passed: true,
      },
      {
        id: "tc-2",
        name: "创建文档",
        input: "在「项目资料」文件夹下创建标题为「Q2 计划」的文档",
        expectedOutput: "返回新文档 URL",
        actualOutput: "返回新文档 URL，文档标题正确",
        passed: true,
      },
      {
        id: "tc-3",
        name: "日历创建事件",
        input: "在明天上午 10:00 创建「团队周会」日历事件，邀请 3 人",
        expectedOutput: "事件创建成功，邀请发出",
        actualOutput: "事件创建成功，但邀请列表解析出现编码异常",
        passed: false,
      },
      {
        id: "tc-4",
        name: "获取群组列表",
        input: "列出当前 Bot 所在的所有群组",
        expectedOutput: "返回群组 id/name 列表",
        actualOutput: "返回群组 id/name 列表（分页正确）",
        passed: true,
      },
      {
        id: "tc-5",
        name: "发送富文本卡片",
        input: "发送包含标题、图片、按钮的交互卡片消息",
        expectedOutput: "卡片消息正常渲染",
        actualOutput: "卡片消息正常渲染，按钮回调地址待配置",
        passed: true,
      },
    ],
  },
};

export const STATS: Stats = {
  totalSkills: 198,
  totalInstalls: 14382,
  weeklyAdditions: 23,
  verifiedCount: 47,   // 3/3
  reviewedCount: 89,   // 2/3
  basicCount: 23,      // 1/3
};

export const CONTRIBUTORS: Contributor[] = [
  { id: "u-001", name: "钟经纬", avatar: "", reputation: 30406, skillCount: 42 },
  { id: "u-002", name: "林晓薇", avatar: "", reputation: 18234, skillCount: 31 },
  { id: "u-003", name: "陈建国", avatar: "", reputation: 12890, skillCount: 27 },
  { id: "u-004", name: "张远航", avatar: "", reputation: 9762, skillCount: 19 },
  { id: "u-005", name: "刘思远", avatar: "", reputation: 7451, skillCount: 16 },
  { id: "u-006", name: "王雨桐", avatar: "", reputation: 5203, skillCount: 14 },
  { id: "u-007", name: "赵明辉", avatar: "", reputation: 3876, skillCount: 11 },
  { id: "u-008", name: "孙婷婷", avatar: "", reputation: 2341, skillCount: 9 },
  { id: "u-009", name: "周宇轩", avatar: "", reputation: 1598, skillCount: 7 },
  { id: "u-010", name: "吴静雯", avatar: "", reputation: 792, skillCount: 4 },
];

export const SKILLS: Skill[] = [
  {
    id: "s-sf",
    name: "skill-finder",
    displayName: "SkillFinder",
    description: "智能技能发现引擎。分析你的任务需求，自动从技能库中匹配并推荐最合适的 Skills，让 Claude 始终拥有完成任务所需的能力。",
    tags: ["技能发现", "推荐", "智能匹配", "效率"],
    installs: 42817,
    author: "OpenClaw 官方",
    authorId: "u-001",
    authorAvatar: "",
    authorReputation: 30406,
    version: "3.1.0",
    installCommand: `/skill install skill-finder`,
    updatedAt: "2026-03-09",
    category: "效率",
    sourcePlatform: "github",
    sourceUrl: "https://github.com/openclaw/skill-finder",
    ecosystems: ["OpenClaw", "CoPaw"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
    certificationDetails: CERT_VERIFIED_SF,
    readme: `# SkillFinder\n\n智能技能发现引擎，让 Claude 自动找到并安装完成任务所需的 Skills。\n\n## 功能\n- 分析对话意图，自动匹配合适技能\n- 一键安装推荐技能组合\n- 持续学习用户偏好，优化推荐结果\n- 支持技能依赖链自动解析\n\n## 安装\n\`\`\`bash\n/skill install skill-finder\n\`\`\`\n\n## 使用示例\n\`\`\`\n帮我分析这份财务报表并生成可视化图表\n→ SkillFinder 自动推荐并安装：金融数据分析 + 数据可视化\n\`\`\`\n\n## 权限声明\n- 读取技能市场列表：需要\n- 自动安装技能：需要用户确认`,
  },
  {
    id: "s-001",
    name: "browser-automation",
    displayName: "浏览器自动化操作",
    description: "让 Claude 能够自动控制浏览器，完成表单填写、页面截图、数据抓取等任务。支持 Playwright 和 Puppeteer 两种驱动。",
    tags: ["浏览器", "自动化", "爬虫", "Playwright"],
    installs: 6194,
    author: "钟经纬",
    authorId: "u-001",
    authorAvatar: "",
    authorReputation: 30406,
    version: "2.3.1",
    installCommand: `/skill install browser-automation`,
    updatedAt: "2026-03-05",
    category: "自动化",
    sourcePlatform: "github",
    sourceUrl: "https://github.com/microsoft/playwright-mcp",
    ecosystems: ["网页", "小红书", "抖音"],
    dependencies: PLAYWRIGHT_DEPS,
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
    certificationDetails: CERT_VERIFIED_BROWSER,
    readme: `# 浏览器自动化操作\n\n让 Claude 能够自动控制浏览器完成复杂任务。\n\n## 功能\n- 打开/关闭标签页\n- 点击、输入、滚动\n- 截图和录屏\n- 数据抓取\n\n## 安装\n\`\`\`bash\n/skill install browser-automation\n\`\`\`\n\n## 使用示例\n\`\`\`\n帮我打开百度，搜索"今日天气"，截图保存\n\`\`\`\n\n## 权限声明\n- 网络访问：需要（访问目标网页）\n- 文件写入：可选（保存截图/数据）\n- 无系统命令执行权限`,
  },
  {
    id: "s-002",
    name: "feishu-integration",
    displayName: "飞书集成套件",
    description: "完整的飞书 OpenAPI 集成，支持发送消息、创建文档、管理日历、机器人交互等全场景飞书操作。",
    tags: ["飞书", "办公", "消息", "文档"],
    installs: 4821,
    author: "林晓薇",
    authorId: "u-002",
    authorAvatar: "",
    authorReputation: 18234,
    version: "1.8.0",
    installCommand: `/skill install feishu-integration`,
    updatedAt: "2026-03-01",
    category: "协作",
    sourcePlatform: "npm",
    sourceUrl: "https://www.npmjs.com/package/feishu-mcp",
    ecosystems: ["飞书"],
    dependencies: FEISHU_DEPS,
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
    certificationDetails: CERT_REVIEWED_FEISHU,
  },
  {
    id: "s-003",
    name: "financial-analysis",
    displayName: "金融数据分析",
    description: "接入多个金融数据源，支持股票行情查询、K 线分析、财报解读、市场情绪分析。内置 A 股、港股、美股数据。",
    tags: ["金融", "股票", "数据分析", "A股"],
    installs: 3912,
    author: "陈建国",
    authorId: "u-003",
    authorAvatar: "",
    authorReputation: 12890,
    version: "1.5.2",
    installCommand: `/skill install financial-analysis`,
    updatedAt: "2026-02-28",
    category: "金融",
    sourcePlatform: "pypi",
    sourceUrl: "https://pypi.org/project/financial-analysis-mcp/",
    ecosystems: ["东方财富", "同花顺"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-004",
    name: "xiaohongshu-publisher",
    displayName: "小红书自动发布",
    description: "自动将内容格式化为小红书风格，添加话题标签，选择最佳发布时间，并自动发布图文笔记。",
    tags: ["小红书", "自动发布", "社交媒体", "内容"],
    installs: 2341,
    author: "王雨桐",
    authorId: "u-006",
    authorAvatar: "",
    authorReputation: 5203,
    version: "1.2.0",
    installCommand: `/skill install xiaohongshu-publisher`,
    updatedAt: "2026-02-25",
    category: "社交媒体",
    sourcePlatform: "smithery",
    sourceUrl: "https://smithery.ai/server/xiaohongshu-publisher",
    ecosystems: ["小红书", "抖音"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "pending" },
    safetyStatus: "reviewed",
  },
  {
    id: "s-005",
    name: "code-reviewer",
    displayName: "代码审查助手",
    description: "自动审查 PR 代码，识别 Bug、安全漏洞、性能问题，生成详细审查报告并发表评论。支持 GitHub 和 GitLab。",
    tags: ["代码审查", "GitHub", "安全", "DevOps"],
    installs: 1987,
    author: "刘思远",
    authorId: "u-005",
    authorAvatar: "",
    authorReputation: 7451,
    version: "1.4.1",
    installCommand: `/skill install code-reviewer`,
    updatedAt: "2026-02-20",
    category: "开发",
    sourcePlatform: "github",
    sourceUrl: "https://github.com/liu-sy/claude-code-reviewer",
    ecosystems: ["GitHub", "GitLab"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-006",
    name: "email-skill",
    displayName: "邮件收发",
    description: "支持 Gmail、Outlook、163 等主流邮箱，实现邮件阅读、分类、回复、发送附件等完整邮件操作。",
    tags: ["邮件", "Gmail", "自动化"],
    installs: 2109,
    author: "周宇轩",
    authorId: "u-009",
    authorAvatar: "",
    authorReputation: 1598,
    version: "1.1.3",
    installCommand: `/skill install email-skill`,
    updatedAt: "2026-02-22",
    category: "效率",
    sourcePlatform: "npm",
    sourceUrl: "https://www.npmjs.com/package/email-mcp",
    ecosystems: ["Gmail", "Outlook", "163邮箱"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "failed" },
    safetyStatus: "reviewed",
  },
  {
    id: "s-007",
    name: "image-generator",
    displayName: "AI 图像生成",
    description: "集成 Flux、SD、DALL-E 等主流图像生成模型，支持文生图、图生图、局部重绘，自动保存到指定位置。",
    tags: ["AI绘图", "Flux", "DALL-E", "图像"],
    installs: 1876,
    author: "吴静雯",
    authorId: "u-010",
    authorAvatar: "",
    authorReputation: 792,
    version: "1.0.2",
    installCommand: `/skill install image-generator`,
    updatedAt: "2026-03-06",
    category: "创意",
    sourcePlatform: "huggingface",
    sourceUrl: "https://huggingface.co/spaces/multimodal-art-projection/image-gen-mcp",
    ecosystems: ["Flux", "DALL-E", "Stable Diffusion"],
    certifiedSteps: { safety: "passed", completeness: "pending", executability: "pending" },
    safetyStatus: "basic",
  },
  {
    id: "s-008",
    name: "data-scraper",
    displayName: "智能数据抓取",
    description: "支持结构化和非结构化数据抓取，自动识别页面内容结构，输出 JSON/CSV/Excel 格式，内置反反爬策略。",
    tags: ["爬虫", "数据抓取", "自动化", "数据"],
    installs: 2765,
    author: "陈建国",
    authorId: "u-003",
    authorAvatar: "",
    authorReputation: 12890,
    version: "3.1.0",
    installCommand: `/skill install data-scraper`,
    updatedAt: "2026-02-26",
    category: "数据",
    sourcePlatform: "pypi",
    sourceUrl: "https://pypi.org/project/data-scraper-mcp/",
    ecosystems: ["网页", "飞书"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "pending" },
    safetyStatus: "reviewed",
  },
  {
    id: "s-009",
    name: "notion-skill",
    displayName: "Notion 操作",
    description: "完整的 Notion API 封装，支持页面创建、数据库操作、块级编辑，让 Claude 成为你的 Notion 助手。",
    tags: ["Notion", "效率", "文档", "数据库"],
    installs: 2234,
    author: "林晓薇",
    authorId: "u-002",
    authorAvatar: "",
    authorReputation: 18234,
    version: "1.7.0",
    installCommand: `/skill install notion-skill`,
    updatedAt: "2026-03-01",
    category: "效率",
    sourcePlatform: "npm",
    sourceUrl: "https://www.npmjs.com/package/notion-mcp",
    ecosystems: ["Notion"],
    dependencies: NOTION_DEPS,
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-010",
    name: "meeting-summary",
    displayName: "会议纪要自动生成",
    description: "实时转录会议语音，自动提炼关键决策、行动项、截止日期，生成结构化纪要并同步到飞书/Notion。",
    tags: ["会议", "转录", "总结", "效率"],
    installs: 1654,
    author: "钟经纬",
    authorId: "u-001",
    authorAvatar: "",
    authorReputation: 30406,
    version: "1.1.0",
    installCommand: `/skill install meeting-summary`,
    updatedAt: "2026-03-06",
    category: "效率",
    sourcePlatform: "huggingface",
    sourceUrl: "https://huggingface.co/spaces/openai/whisper-meeting-mcp",
    ecosystems: ["飞书", "Notion"],
    certifiedSteps: { safety: "pending", completeness: "pending", executability: "pending" },
    safetyStatus: "pending",
  },
  {
    id: "s-011",
    name: "github-skill",
    displayName: "GitHub 操作",
    description: "管理仓库、Issue、PR，自动化 CI/CD 流程，查询代码变更历史，支持 GitHub Actions 触发。",
    tags: ["GitHub", "DevOps", "代码", "CI/CD"],
    installs: 3102,
    author: "张远航",
    authorId: "u-004",
    authorAvatar: "",
    authorReputation: 9762,
    version: "2.0.1",
    installCommand: `/skill install github-skill`,
    updatedAt: "2026-03-03",
    category: "开发",
    sourcePlatform: "github",
    sourceUrl: "https://github.com/github/github-mcp-server",
    ecosystems: ["GitHub", "GitHub Actions"],
    dependencies: GITHUB_DEPS,
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-013",
    name: "douyin-publisher",
    displayName: "抖音内容发布",
    description: "将脚本自动转化为抖音竖屏视频草稿，支持封面生成、字幕烧录、话题打标、定时发布，适配抖音创作者服务平台。",
    tags: ["抖音", "视频", "自动发布", "内容创作"],
    installs: 1543,
    author: "赵明辉",
    authorId: "u-007",
    authorAvatar: "",
    authorReputation: 3876,
    version: "1.0.5",
    installCommand: `/skill install douyin-publisher`,
    updatedAt: "2026-03-04",
    category: "社交媒体",
    sourcePlatform: "smithery",
    sourceUrl: "https://smithery.ai/server/douyin-publisher",
    ecosystems: ["抖音", "小红书"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "failed" },
    safetyStatus: "reviewed",
  },
  {
    id: "s-014",
    name: "calendar-scheduler",
    displayName: "智能日程管理",
    description: "接入 Google Calendar、飞书日历，自动识别消息中的时间意图，一键创建会议、发送邀请、设置提醒，支持多时区协调。",
    tags: ["日历", "效率", "飞书", "Google"],
    installs: 1378,
    author: "孙婷婷",
    authorId: "u-008",
    authorAvatar: "",
    authorReputation: 2341,
    version: "1.2.3",
    installCommand: `/skill install calendar-scheduler`,
    updatedAt: "2026-03-02",
    category: "效率",
    sourcePlatform: "npm",
    sourceUrl: "https://www.npmjs.com/package/calendar-mcp",
    ecosystems: ["飞书", "Google Calendar"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-012",
    name: "web-search",
    displayName: "联网搜索增强",
    description: "集成多搜索引擎，支持实时信息检索、深度网页内容提取、来源可信度评估，自动去重聚合。",
    tags: ["搜索", "联网", "实时信息", "研究"],
    installs: 5431,
    author: "刘思远",
    authorId: "u-005",
    authorAvatar: "",
    authorReputation: 7451,
    version: "1.3.0",
    installCommand: `/skill install web-search`,
    updatedAt: "2026-03-07",
    category: "信息",
    sourcePlatform: "smithery",
    sourceUrl: "https://smithery.ai/server/brave-search",
    ecosystems: ["Google", "Bing", "知乎"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
];

export const ACTIVITY: ActivityItem[] = [
  { id: "a-001", type: "publish", skillName: "会议纪要自动生成", skillId: "s-010", author: "钟经纬", authorAvatar: "", time: "2分钟前", version: "1.1.0" },
  { id: "a-002", type: "update", skillName: "浏览器自动化操作", skillId: "s-001", author: "钟经纬", authorAvatar: "", time: "15分钟前", version: "2.3.1" },
  { id: "a-003", type: "publish", skillName: "AI 图像生成", skillId: "s-007", author: "吴静雯", authorAvatar: "", time: "1小时前", version: "1.0.2" },
  { id: "a-004", type: "update", skillName: "联网搜索增强", skillId: "s-012", author: "刘思远", authorAvatar: "", time: "3小时前", version: "1.3.0" },
  { id: "a-005", type: "publish", skillName: "GitHub 操作", skillId: "s-011", author: "张远航", authorAvatar: "", time: "5小时前", version: "2.0.1" },
  { id: "a-006", type: "update", skillName: "飞书集成套件", skillId: "s-002", author: "林晓薇", authorAvatar: "", time: "8小时前", version: "1.8.0" },
  { id: "a-007", type: "publish", skillName: "Notion 操作", skillId: "s-009", author: "林晓薇", authorAvatar: "", time: "1天前", version: "1.7.0" },
  { id: "a-008", type: "update", skillName: "金融数据分析", skillId: "s-003", author: "陈建国", authorAvatar: "", time: "2天前", version: "1.5.2" },
];

export const FEATURED_SKILL_IDS = ["s-012", "s-001", "s-011", "s-002"];

export const CATEGORIES = ["全部", "自动化", "协作", "金融", "社交媒体", "开发", "数据", "效率", "创意", "信息"];

// 只有安全性通过才可上架
export const VISIBLE_SKILLS = SKILLS.filter((skill) => skill.certifiedSteps.safety === "passed");

export const ECOSYSTEMS = [
  "全部",
  ...Array.from(new Set(VISIBLE_SKILLS.flatMap((skill) => skill.ecosystems))),
];
