import { Skill, Contributor, ActivityItem, Stats, SkillDependency } from "./types";

// Reusable dependency sets
const PLAYWRIGHT_DEPS: SkillDependency[] = [
  { name: "PLAYWRIGHT_BROWSER_PATH", type: "env", required: false, description: "Playwright 浏览器可执行路径", default: "自动检测" },
  { name: "playwright", type: "package", required: true, description: "Playwright 自动化库 >= 1.30.0" },
  { name: "chromium / firefox / webkit", type: "tool", required: true, description: "至少安装一种浏览器驱动" },
];

const FEISHU_DEPS: SkillDependency[] = [
  { name: "FEISHU_APP_ID", type: "env", required: true, description: "飞书开放平台应用 App ID" },
  { name: "FEISHU_APP_SECRET", type: "env", required: true, description: "飞书开放平台应用 App Secret" },
  { name: "feishu-sdk", type: "package", required: true, description: "飞书 OpenAPI SDK >= 2.0.0" },
];

const GITHUB_DEPS: SkillDependency[] = [
  { name: "GITHUB_TOKEN", type: "env", required: true, description: "GitHub Personal Access Token（需 repo 权限）" },
  { name: "octokit", type: "package", required: true, description: "GitHub REST API 客户端 >= 3.0.0" },
];

const NOTION_DEPS: SkillDependency[] = [
  { name: "NOTION_API_KEY", type: "env", required: true, description: "Notion Integration Token" },
  { name: "NOTION_DATABASE_ID", type: "env", required: false, description: "默认写入的数据库 ID", default: "运行时指定" },
  { name: "@notionhq/client", type: "package", required: true, description: "Notion 官方 SDK >= 2.2.0" },
];

export const STATS: Stats = {
  totalSkills: 198,
  totalInstalls: 14382,
  weeklyAdditions: 23,
  verifiedCount: 47,   // 3/3
  reviewedCount: 89,   // 2/3
  basicCount: 23,      // 1/3
};

export const CONTRIBUTORS: Contributor[] = [
  { id: "u-001", name: "钟经纬", avatar: "", reputation: 30406, skillCount: 42 },
  { id: "u-002", name: "林晓薇", avatar: "", reputation: 18234, skillCount: 31 },
  { id: "u-003", name: "陈建国", avatar: "", reputation: 12890, skillCount: 27 },
  { id: "u-004", name: "张远航", avatar: "", reputation: 9762, skillCount: 19 },
  { id: "u-005", name: "刘思远", avatar: "", reputation: 7451, skillCount: 16 },
  { id: "u-006", name: "王雨桐", avatar: "", reputation: 5203, skillCount: 14 },
  { id: "u-007", name: "赵明辉", avatar: "", reputation: 3876, skillCount: 11 },
  { id: "u-008", name: "孙婷婷", avatar: "", reputation: 2341, skillCount: 9 },
  { id: "u-009", name: "周宇轩", avatar: "", reputation: 1598, skillCount: 7 },
  { id: "u-010", name: "吴静雯", avatar: "", reputation: 792, skillCount: 4 },
];

export const SKILLS: Skill[] = [
  {
    id: "s-001",
    name: "browser-automation",
    displayName: "浏览器自动化操作",
    description: "让 Claude 能够自动控制浏览器，完成表单填写、页面截图、数据抓取等任务。支持 Playwright 和 Puppeteer 两种驱动。",
    tags: ["浏览器", "自动化", "爬虫", "Playwright"],
    installs: 6194,
    totalStars: 312,
    author: "钟经纬",
    authorId: "u-001",
    authorAvatar: "",
    authorReputation: 30406,
    version: "2.3.1",
    installCommand: `/skill install browser-automation`,
    updatedAt: "2026-03-05",
    category: "自动化",
    sourcePlatform: "github",
    sourceUrl: "https://github.com/microsoft/playwright-mcp",
    ecosystems: ["网页", "小红书", "抖音"],
    dependencies: PLAYWRIGHT_DEPS,
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
    readme: `# 浏览器自动化操作\n\n让 Claude 能够自动控制浏览器完成复杂任务。\n\n## 功能\n- 打开/关闭标签页\n- 点击、输入、滚动\n- 截图和录屏\n- 数据抓取\n\n## 安装\n\`\`\`bash\n/skill install browser-automation\n\`\`\`\n\n## 使用示例\n\`\`\`\n帮我打开百度，搜索"今日天气"，截图保存\n\`\`\`\n\n## 权限声明\n- 网络访问：需要（访问目标网页）\n- 文件写入：可选（保存截图/数据）\n- 无系统命令执行权限`,
  },
  {
    id: "s-002",
    name: "feishu-integration",
    displayName: "飞书集成套件",
    description: "完整的飞书 OpenAPI 集成，支持发送消息、创建文档、管理日历、机器人交互等全场景飞书操作。",
    tags: ["飞书", "办公", "消息", "文档"],
    installs: 4821,
    totalStars: 245,
    author: "林晓薇",
    authorId: "u-002",
    authorAvatar: "",
    authorReputation: 18234,
    version: "1.8.0",
    installCommand: `/skill install feishu-integration`,
    updatedAt: "2026-03-01",
    category: "协作",
    sourcePlatform: "npm",
    sourceUrl: "https://www.npmjs.com/package/feishu-mcp",
    ecosystems: ["飞书"],
    dependencies: FEISHU_DEPS,
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-003",
    name: "financial-analysis",
    displayName: "金融数据分析",
    description: "接入多个金融数据源，支持股票行情查询、K 线分析、财报解读、市场情绪分析。内置 A 股、港股、美股数据。",
    tags: ["金融", "股票", "数据分析", "A股"],
    installs: 3912,
    totalStars: 198,
    author: "陈建国",
    authorId: "u-003",
    authorAvatar: "",
    authorReputation: 12890,
    version: "1.5.2",
    installCommand: `/skill install financial-analysis`,
    updatedAt: "2026-02-28",
    category: "金融",
    sourcePlatform: "pypi",
    sourceUrl: "https://pypi.org/project/financial-analysis-mcp/",
    ecosystems: ["东方财富", "同花顺"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-004",
    name: "xiaohongshu-publisher",
    displayName: "小红书自动发布",
    description: "自动将内容格式化为小红书风格，添加话题标签，选择最佳发布时间，并自动发布图文笔记。",
    tags: ["小红书", "自动发布", "社交媒体", "内容"],
    installs: 2341,
    totalStars: 156,
    author: "王雨桐",
    authorId: "u-006",
    authorAvatar: "",
    authorReputation: 5203,
    version: "1.2.0",
    installCommand: `/skill install xiaohongshu-publisher`,
    updatedAt: "2026-02-25",
    category: "社交媒体",
    sourcePlatform: "smithery",
    sourceUrl: "https://smithery.ai/server/xiaohongshu-publisher",
    ecosystems: ["小红书", "抖音"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "pending" },
    safetyStatus: "reviewed",
  },
  {
    id: "s-005",
    name: "code-reviewer",
    displayName: "代码审查助手",
    description: "自动审查 PR 代码，识别 Bug、安全漏洞、性能问题，生成详细审查报告并发表评论。支持 GitHub 和 GitLab。",
    tags: ["代码审查", "GitHub", "安全", "DevOps"],
    installs: 1987,
    totalStars: 143,
    author: "刘思远",
    authorId: "u-005",
    authorAvatar: "",
    authorReputation: 7451,
    version: "1.4.1",
    installCommand: `/skill install code-reviewer`,
    updatedAt: "2026-02-20",
    category: "开发",
    sourcePlatform: "github",
    sourceUrl: "https://github.com/liu-sy/claude-code-reviewer",
    ecosystems: ["GitHub", "GitLab"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-006",
    name: "email-skill",
    displayName: "邮件收发",
    description: "支持 Gmail、Outlook、163 等主流邮箱，实现邮件阅读、分类、回复、发送附件等完整邮件操作。",
    tags: ["邮件", "Gmail", "自动化"],
    installs: 2109,
    totalStars: 134,
    author: "周宇轩",
    authorId: "u-009",
    authorAvatar: "",
    authorReputation: 1598,
    version: "1.1.3",
    installCommand: `/skill install email-skill`,
    updatedAt: "2026-02-22",
    category: "效率",
    sourcePlatform: "npm",
    sourceUrl: "https://www.npmjs.com/package/email-mcp",
    ecosystems: ["Gmail", "Outlook", "163邮箱"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "failed" },
    safetyStatus: "reviewed",
  },
  {
    id: "s-007",
    name: "image-generator",
    displayName: "AI 图像生成",
    description: "集成 Flux、SD、DALL-E 等主流图像生成模型，支持文生图、图生图、局部重绘，自动保存到指定位置。",
    tags: ["AI绘图", "Flux", "DALL-E", "图像"],
    installs: 1876,
    totalStars: 178,
    author: "吴静雯",
    authorId: "u-010",
    authorAvatar: "",
    authorReputation: 792,
    version: "1.0.2",
    installCommand: `/skill install image-generator`,
    updatedAt: "2026-03-06",
    category: "创意",
    sourcePlatform: "huggingface",
    sourceUrl: "https://huggingface.co/spaces/multimodal-art-projection/image-gen-mcp",
    ecosystems: ["Flux", "DALL-E", "Stable Diffusion"],
    certifiedSteps: { safety: "passed", completeness: "pending", executability: "pending" },
    safetyStatus: "basic",
  },
  {
    id: "s-008",
    name: "data-scraper",
    displayName: "智能数据抓取",
    description: "支持结构化和非结构化数据抓取，自动识别页面内容结构，输出 JSON/CSV/Excel 格式，内置反反爬策略。",
    tags: ["爬虫", "数据抓取", "自动化", "数据"],
    installs: 2765,
    totalStars: 167,
    author: "陈建国",
    authorId: "u-003",
    authorAvatar: "",
    authorReputation: 12890,
    version: "3.1.0",
    installCommand: `/skill install data-scraper`,
    updatedAt: "2026-02-26",
    category: "数据",
    sourcePlatform: "pypi",
    sourceUrl: "https://pypi.org/project/data-scraper-mcp/",
    ecosystems: ["网页", "飞书"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "pending" },
    safetyStatus: "reviewed",
  },
  {
    id: "s-009",
    name: "notion-skill",
    displayName: "Notion 操作",
    description: "完整的 Notion API 封装，支持页面创建、数据库操作、块级编辑，让 Claude 成为你的 Notion 助手。",
    tags: ["Notion", "效率", "文档", "数据库"],
    installs: 2234,
    totalStars: 156,
    author: "林晓薇",
    authorId: "u-002",
    authorAvatar: "",
    authorReputation: 18234,
    version: "1.7.0",
    installCommand: `/skill install notion-skill`,
    updatedAt: "2026-03-01",
    category: "效率",
    sourcePlatform: "npm",
    sourceUrl: "https://www.npmjs.com/package/notion-mcp",
    ecosystems: ["Notion"],
    dependencies: NOTION_DEPS,
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-010",
    name: "meeting-summary",
    displayName: "会议纪要自动生成",
    description: "实时转录会议语音，自动提炼关键决策、行动项、截止日期，生成结构化纪要并同步到飞书/Notion。",
    tags: ["会议", "转录", "总结", "效率"],
    installs: 1654,
    totalStars: 134,
    author: "钟经纬",
    authorId: "u-001",
    authorAvatar: "",
    authorReputation: 30406,
    version: "1.1.0",
    installCommand: `/skill install meeting-summary`,
    updatedAt: "2026-03-06",
    category: "效率",
    sourcePlatform: "huggingface",
    sourceUrl: "https://huggingface.co/spaces/openai/whisper-meeting-mcp",
    ecosystems: ["飞书", "Notion"],
    certifiedSteps: { safety: "pending", completeness: "pending", executability: "pending" },
    safetyStatus: "pending",
  },
  {
    id: "s-011",
    name: "github-skill",
    displayName: "GitHub 操作",
    description: "管理仓库、Issue、PR，自动化 CI/CD 流程，查询代码变更历史，支持 GitHub Actions 触发。",
    tags: ["GitHub", "DevOps", "代码", "CI/CD"],
    installs: 3102,
    totalStars: 211,
    author: "张远航",
    authorId: "u-004",
    authorAvatar: "",
    authorReputation: 9762,
    version: "2.0.1",
    installCommand: `/skill install github-skill`,
    updatedAt: "2026-03-03",
    category: "开发",
    sourcePlatform: "github",
    sourceUrl: "https://github.com/github/github-mcp-server",
    ecosystems: ["GitHub", "GitHub Actions"],
    dependencies: GITHUB_DEPS,
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-013",
    name: "douyin-publisher",
    displayName: "抖音内容发布",
    description: "将脚本自动转化为抖音竖屏视频草稿，支持封面生成、字幕烧录、话题打标、定时发布，适配抖音创作者服务平台。",
    tags: ["抖音", "视频", "自动发布", "内容创作"],
    installs: 1543,
    totalStars: 112,
    author: "赵明辉",
    authorId: "u-007",
    authorAvatar: "",
    authorReputation: 3876,
    version: "1.0.5",
    installCommand: `/skill install douyin-publisher`,
    updatedAt: "2026-03-04",
    category: "社交媒体",
    sourcePlatform: "smithery",
    sourceUrl: "https://smithery.ai/server/douyin-publisher",
    ecosystems: ["抖音", "小红书"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "failed" },
    safetyStatus: "reviewed",
  },
  {
    id: "s-014",
    name: "calendar-scheduler",
    displayName: "智能日程管理",
    description: "接入 Google Calendar、飞书日历，自动识别消息中的时间意图，一键创建会议、发送邀请、设置提醒，支持多时区协调。",
    tags: ["日历", "效率", "飞书", "Google"],
    installs: 1378,
    totalStars: 98,
    author: "孙婷婷",
    authorId: "u-008",
    authorAvatar: "",
    authorReputation: 2341,
    version: "1.2.3",
    installCommand: `/skill install calendar-scheduler`,
    updatedAt: "2026-03-02",
    category: "效率",
    sourcePlatform: "npm",
    sourceUrl: "https://www.npmjs.com/package/calendar-mcp",
    ecosystems: ["飞书", "Google Calendar"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
  {
    id: "s-012",
    name: "web-search",
    displayName: "联网搜索增强",
    description: "集成多搜索引擎，支持实时信息检索、深度网页内容提取、来源可信度评估，自动去重聚合。",
    tags: ["搜索", "联网", "实时信息", "研究"],
    installs: 5431,
    totalStars: 287,
    author: "刘思远",
    authorId: "u-005",
    authorAvatar: "",
    authorReputation: 7451,
    version: "1.3.0",
    installCommand: `/skill install web-search`,
    updatedAt: "2026-03-07",
    category: "信息",
    sourcePlatform: "smithery",
    sourceUrl: "https://smithery.ai/server/brave-search",
    ecosystems: ["Google", "Bing", "知乎"],
    certifiedSteps: { safety: "passed", completeness: "passed", executability: "passed" },
    safetyStatus: "verified",
  },
];

export const ACTIVITY: ActivityItem[] = [
  { id: "a-001", type: "publish", skillName: "会议纪要自动生成", skillId: "s-010", author: "钟经纬", authorAvatar: "", time: "2分钟前", version: "1.1.0" },
  { id: "a-002", type: "update", skillName: "浏览器自动化操作", skillId: "s-001", author: "钟经纬", authorAvatar: "", time: "15分钟前", version: "2.3.1" },
  { id: "a-003", type: "publish", skillName: "AI 图像生成", skillId: "s-007", author: "吴静雯", authorAvatar: "", time: "1小时前", version: "1.0.2" },
  { id: "a-004", type: "update", skillName: "联网搜索增强", skillId: "s-012", author: "刘思远", authorAvatar: "", time: "3小时前", version: "1.3.0" },
  { id: "a-005", type: "publish", skillName: "GitHub 操作", skillId: "s-011", author: "张远航", authorAvatar: "", time: "5小时前", version: "2.0.1" },
  { id: "a-006", type: "update", skillName: "飞书集成套件", skillId: "s-002", author: "林晓薇", authorAvatar: "", time: "8小时前", version: "1.8.0" },
  { id: "a-007", type: "publish", skillName: "Notion 操作", skillId: "s-009", author: "林晓薇", authorAvatar: "", time: "1天前", version: "1.7.0" },
  { id: "a-008", type: "update", skillName: "金融数据分析", skillId: "s-003", author: "陈建国", authorAvatar: "", time: "2天前", version: "1.5.2" },
];

export const FEATURED_SKILL_IDS = ["s-012", "s-001", "s-011", "s-002"];

export const CATEGORIES = ["全部", "自动化", "协作", "金融", "社交媒体", "开发", "数据", "效率", "创意", "信息"];

// 只有安全性通过才可上架
export const VISIBLE_SKILLS = SKILLS.filter((skill) => skill.certifiedSteps.safety === "passed");

export const ECOSYSTEMS = [
  "全部",
  ...Array.from(new Set(VISIBLE_SKILLS.flatMap((skill) => skill.ecosystems))),
];
